### PR TITLE
Features/display

### PR DESCRIPTION
**Pull request by MattWongCode4U**
Pressing search button now displays a table with the selected course from dropdown. Still neeeds to be able to display course info.

### CODE REVIEW

**Comment by srepollock** [comment]
@MattWongCode4U looks fine. Just add in the code that I posted and fiddle around with that see what you can do. Should work for the most part

**Comment by srepollock** [comment]
@MattWongCode4U got it displaying for just classes only. Take a look at how this works [here](https://github.com/srepollock/comp4711-lab07/tree/feature/table). Look in the models/Timetable.php and controllers/Welcome.php. Focus on the find functions in Timetable and maybe break down the display in the Welcome controller into a function. @mssshu work with Matt on this. Figure out how we can search by class/day/time (or just class time? or even by teacher? idk what he wants really).

**Comment by srepollock** [comment]
I guess this is ok @MattWongCode4U

**Comment by MattWongCode4U** [comment]
@srepollock thanks babs

**Pull request merged**
